[
	"RHS_A10",
	"B_Plane_CAS_01_dynamicLoadout_F",
	"RHS_AN2_B",
	"RHS_C130J",
	"C_Plane_Civil_01_F",
	"C_Plane_Civil_01_racing_F",
	"B_Plane_Fighter_01_F",
	"I_Plane_Fighter_04_F",
	"rhssaf_airforce_l_18",
	"RHS_L39_cdf_b_cdf",
	"RHS_l159_cdf_b_CDF",
	"RHSGREF_cdf_b_su25",
	"B_UAV_02_dynamicLoadout_f",
	"RHSGREF_A29B_HIDF"
];