[
	"RHS_A10",
	"B_Plane_CAS_01_dynamicLoadout_F",
	"RHS_AN2_B",
	"RHS_C130J",
	"C_Plane_Civil_01_F",
	"C_Plane_Civil_01_racing_F",
	"B_Plane_Fighter_01_F",
	"I_Plane_Fighter_04_F",
	"RHS_l159_cdf_b_CDF",
	"B_UAV_02_dynamicLoadout_f",
	"RHSGREF_A29B_HIDF",
	"B_UAV_05_F"
];